/**
 * Named audit-log action constants.
 * Every mutating endpoint records exactly one of these in activity_logs.
 */

export const ACTIVITY_ACTIONS = {
  // Auth & profile
  REGISTER_USER: "REGISTER_USER",
  UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",

  // Organizations
  CREATE_ORGANIZATION: "CREATE_ORGANIZATION",
  ADD_ORG_MEMBER: "ADD_ORG_MEMBER",
  UPDATE_ORG_MEMBER_ROLE: "UPDATE_ORG_MEMBER_ROLE",
  REMOVE_ORG_MEMBER: "REMOVE_ORG_MEMBER",

  // Shipment lifecycle
  CREATE_SHIPMENT: "CREATE_SHIPMENT",
  UPDATE_SHIPMENT: "UPDATE_SHIPMENT",
  SUBMIT_SHIPMENT: "SUBMIT_SHIPMENT",
  CANCEL_SHIPMENT: "CANCEL_SHIPMENT",
  ASSIGN_CARRIER: "ASSIGN_CARRIER",
  ASSIGN_CLEARING_AGENT: "ASSIGN_CLEARING_AGENT",
  SUBMIT_QUOTE: "SUBMIT_QUOTE",
  APPROVE_QUOTE: "APPROVE_QUOTE",

  // Documents
  UPLOAD_SHIPMENT_DOCUMENT: "UPLOAD_SHIPMENT_DOCUMENT",
  VERIFY_SHIPMENT_DOCUMENT: "VERIFY_SHIPMENT_DOCUMENT",
  REJECT_SHIPMENT_DOCUMENT: "REJECT_SHIPMENT_DOCUMENT",

  // Operational execution
  ASSIGN_EXECUTION: "ASSIGN_EXECUTION",
  RECORD_SHIPMENT_EVENT: "RECORD_SHIPMENT_EVENT",
  CAPTURE_POD: "CAPTURE_POD",
  COMPLETE_SHIPMENT: "COMPLETE_SHIPMENT",

  // Payments
  RECORD_PAYMENT: "RECORD_PAYMENT",
  MARK_PAYMENT_PAID: "MARK_PAYMENT_PAID",

  // Exceptions
  OPEN_EXCEPTION: "OPEN_EXCEPTION",
  RESOLVE_EXCEPTION: "RESOLVE_EXCEPTION",

  // Fleet
  CREATE_VEHICLE: "CREATE_VEHICLE",
  UPDATE_VEHICLE: "UPDATE_VEHICLE",
  DELETE_VEHICLE: "DELETE_VEHICLE",

  // Driver verification (platform admin)
  SUBMIT_DRIVER_PROFILE: "SUBMIT_DRIVER_PROFILE",
  VERIFY_DRIVER: "VERIFY_DRIVER",
  REJECT_DRIVER: "REJECT_DRIVER",
};
